<a href="https://colab.research.google.com/github/kxjw98/factor/blob/main/factor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install factor_analyzer

In [2]:
#librerias
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import bartlett

In [32]:
from google.colab import files
uploaded = files.upload()

Saving sv - Sheet1.csv to sv - Sheet1 (1).csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['sv - Sheet1.csv']))
df.info()

In [35]:
#error
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity 
chi_square_value,p_value=calculate_bartlett_sphericity(df) 
chi_square_value,p_value

/usr/local/lib/python3.7/dist-packages/factor_analyzer/factor_analyzer.py:111: RuntimeWarning: divide by zero encountered in log
  statistic = -np.log(corr_det) * (n - 1 - (2 * p + 5) / 6)


(-inf, 1.0)

In [ ]:
import seaborn as sns
plt.figure(figsize=(30,20))
c= df.corr()
sns.heatmap(c, annot=True, linewidths=.5)
#df.corr()

In [37]:
#define x and y
x=df.drop(['total_acci'], axis=1).values
y=df['total_acci'].values

In [38]:
print(x)
print(y)

[[   88  1016  3524 ...   393   613     0]
 [   83  1247  4981 ...   514   784   175]
 [   78  1122  5494 ...   851  1410   309]
 ...
 [  146   987 14052 ...  3205  6208  3208]
 [  152   991 12259 ...  3053  5927  2042]
 [  147   836  9067 ...  2221  4458  1609]]
[ 4628  6311  6694  8256 10634 11055 10751  9793 10528 10489 11642 14713
 14207 14576 12099 12143 14818 13990 15185 13402 10050]


In [48]:
#Split the data set in training set and test set 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=0)

In [49]:
#train the model on the training set 
from sklearn.linear_model import LinearRegression 
ml=LinearRegression()
ml.fit(x_train,y_train)

LinearRegression()

In [50]:
y_pred=ml.predict(x_test)
print(y_pred)

[10585.25005859 14645.20216161  9936.27775446  6302.07373626
 14681.67294645 11683.71577781]


In [51]:
ml.predict([[88,1016,3524,419,338,427,371,397,363,329,341,428,443,290,482,635,621,597,644,732,775,624,6212,322,221,160,352,1486,420,143,10,227,109,147,4627,1,0,4546,15,40,20,7,4353,275,3258,220,9,215,88,29,537,2,2,20,23,225,117,129,100,84,87,60,83,101,210,216,220,245,198,225,252,281,243,280,297,239,284,220,232,225,81,3829,276,393,613,0]])

array([4628.])

In [52]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9995196300955234